server: 
  port: 8082

databases: 
  - user: admin 
    password: admin 
    host: localhost
    dbName: shopDev
  - user: user 
    password: user 
    host: localhost
    dbName: user
 
security: 
  jwt: 
    key: abc123